### ISSUE TITLE
Different results between './manage.py test' and 'circleci local execute'

### ISSUE THREAD

**Issue by robotichead** [CircleCI-Public/circleci-cli#591] opened 2021-04-17 08:30 UTC
## Meta:

**CircleCI CLI Version:**
0.1.15195+595cc9e (homebrew)

**Operating System:**
- macOS Big Sur
- Linux Ubuntu 20.04

**CircleCI CLI Diagnostic:**
```
⠦No updates found. 
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/luke/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
Error: please set a token with 'circleci setup'
You can create a new personal API token here:
h
```

---

## Current behavior:
This is a weird one which I can not put my finger on a solution for. I am getting two different results when testing manually on my local system vs. when I am using CircleCI or CircleCI-cli.

The code in question is this particular section - https://github.com/robotichead/NearBeach/blob/1fc20fbbb5599fb45457d3bf40475fe946fe8001/NearBeach/tests/test_user_permissions.py#L258

So this test does the following;
1. Log in as a read only user - success
2. Go to /task_information/1 - success, user has permission
3. Go to /task_information/2 <- this is where I get the conflicting results

- When I manually test this, the user gets redirected to a 403 page.
- When I run `./manage.py test`, the test result comes back as a pass - i.e. the user gets redirected to a 403 page.
- When I run ` coverage run --omit='venv/*' manage.py test`, the test result comes back as a pass - i.e the user gets redirected to a 403 page
- When I run `circleci local execute`, the test results comes back as a fail - i.e. the user actually has access

I am using fixtures to load the exact same data into the database each time. I am not familiar with docker enough to jump into the container to debug what exactly is happening. When I comment out these tests (you'll be able to see similar run tests above), all other tests work perfectly fine.

## Expected behavior:
CircleCI to have the same results as the prior two commands

## When did this begin / Was this previously working?:
As I have started re-writing tests - I have only just noticed this.

## Additional Information:
https://github.com/robotichead/NearBeach <- the project I am writing tests for.

```
======================================================================
FAIL: test_task_permissions (NearBeach.tests.test_user_permissions.ReadOnlyPermissionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/circleci/project/NearBeach/tests/test_user_permissions.py", line 258, in test_task_permissions
self.assertEqual(response.status_code, 403)
AssertionError: 200 != 403
```

**Comment by robotichead** [comment] 2021-05-18 03:34
Any updates on this?

**Comment by robotichead** [comment] 2021-05-28 00:15
I have dug further into this issue. It looks like the `raise PermissionDenied` is being interpreted incorrectly, and sending a Http Status of 200, instead of Http Status 403. 

https://github.com/robotichead/NearBeach/blob/8735498fe7cfb8cad37daca0809d749259778371/NearBeach/decorators/check_user_permissions.py#L127 <- this is the exact line the above test hits (expected).

In normal cases, this decorator stops the function from running, and returns a 403 (permission denied). In CircleCI the decorator still stops, but returns the wrong error code.

**Comment by johnswanson** [comment] 2021-08-16 12:53
Hi @robotichead, sorry for the late response.

We sometimes run into issues like this internally on our own projects. They can pretty much invariably be tracked down to some difference between the environment locally and on circleci (env vars are a huge source here).

One thing I very frequently use to debug issues like this is the "rerun with SSH" feature (in the web UI for the job itself, not the CLI). You can rerun your job, SSH into it, and run whatever commands you need to track down the issue there.

The problem is that your application is doing different things in different environments, so that's a good way to figure out exactly what aspect of the environment is causing the different behavior.

But - I'm going to close this issue for now though as I don't think this is a bug in the CLI.

**Closed by johnswanson** 2021-08-16 12:53 UTC
Labels: bug
