### ISSUE TITLE
build or install on Apple M1

### ISSUE THREAD

**Issue by llaenowyd** [CircleCI-Public/circleci-cli#579] opened 2021-02-24 15:27 UTC
## Meta:

**CircleCI CLI Version:**
latest

**Operating System:**
BigSur

**CircleCI CLI Diagnostic:**
[Following brew instructions](https://github.com/circleci/circleci-docs/issues/5099):
```
Last 15 lines from /Users/collin/Library/Logs/Homebrew/circleci/01.make:
2021-02-21 10:03:26 -0500

make
pack

bash .circleci/pack.sh
make: *** [pack] Error 1
```

Following [alternative installation method](https://circleci.com/docs/2.0/local-cli/#alternative-installation-method):
```
% curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | bash
Starting installation.
Installing CircleCI CLI v0.1.14966
Installing to /Volumes/T7/bin/circleci
An error occured installing the tool.
The contents of the directory /var/folders/vx/zz3mf6ys7dl76ystc7jwqynm0000gn/T/tmp.iRcDaIbA have been left in place to help to debug the issue.
```

but
```
%file /var/folders/vx/zz3mf6ys7dl76ystc7jwqynm0000gn/T/tmp.iRcDaIbA/circleci
/var/folders/vx/zz3mf6ys7dl76ystc7jwqynm0000gn/T/tmp.iRcDaIbA/circleci: Mach-O 64-bit executable x86_64
```

and
```
% /var/folders/vx/zz3mf6ys7dl76ystc7jwqynm0000gn/T/tmp.iRcDaIbA/circleci version  
0.1.14966+1cd24ae (release)
```

Looks like a scripting problem in both cases TBH, possibly not directly due to the cpu arch?

**Comment by gmemstr** [comment] 2021-03-11 11:45
@llaenowyd What does `install --help` return on your machine? I don't _think_ this is related to the CPU arch, and judging by the output this is the last step it attempted before erroring out.

**Comment by llaenowyd** [comment] 2021-03-11 14:17
That's clarifying - if it's intended to be run with elevated privilege, I didn't realize.

```
% bash ./install.sh --help
Starting installation.
Installing CircleCI CLI v0.1.15108
Installing to /usr/local/bin
install: /usr/local/bin: Permission denied
An error occured installing the tool.
The contents of the directory /var/folders/vx/zz3mf6ys7dl76ystc7jwqynm0000gn/T/tmp.2QIiGC4J have been left in place to help to debug the issue.
```

**Comment by gmemstr** [comment] 2021-03-11 14:54
@llaenowyd My bad - `install` is a command run within the install script to move the files to the correct place, which I believe is built-in to macOS. We do note the requirement for elevated privs here: https://github.com/CircleCI-Public/circleci-cli#install-script

Unfortunately, I don't know for sure why the brew step is failing -- I don't currently have a mac to test it with.

**Comment by llaenowyd** [comment] 2021-03-11 17:40
Oh I did not know that, ok. I'm discovering that homebrew introduces more variables with arm64 support - somewhat averse to using it until there's an "all good for m1" announcement, and as of now, nothing is installed with it:

```
% brew list
%
```

```
% install --help
install: illegal option -- -
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
```

```
% file `which install`
/usr/bin/install: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/usr/bin/install (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/bin/install (for architecture arm64e):	Mach-O 64-bit executable arm64e
```

**Comment by M157q** [comment] 2021-05-25 16:18
Encountered this same problem on MacBook with M1 chip.
I can confirm that `sudo bash ./install.sh` did successfully install `circleci` with Mach-O x86_64 binary format for me and it works on MacBook with M1 chip.
```
$ file /usr/local/bin/circleci
/usr/local/bin/circleci: Mach-O 64-bit executable x86_64
```

The reason why `brew install circleci` failed is that no pre-compiled bottle could be found.
(Check this PR which is labeled with `no ARM bottle`: https://github.com/Homebrew/homebrew-core/pull/76657)

Follow the suggestion in error message and use `brew install --build-from-source circleci` to install `circleci` still got the error below:
```
2021-05-25 23:37:25 +0800

make
pack

bash .circleci/pack.sh
make: *** [pack] Error 1
```

After tracing the source code, I think the problem is that Homebrew Formula use `make pack` before building the binary: https://github.com/Homebrew/homebrew-core/blob/70c30cc5a55029f0c5d774e314005cd68a370030/Formula/circleci.rb#L32
which execute `bash .circleci/pack.sh`
Take a look at `.circleci/pack.sh`:https://github.com/CircleCI-Public/circleci-cli/blob/605a6173ef1ac57573e64785d84c51db9d47b696/.circleci/pack.sh#L15-L32

The values of `uname -a` and `$OSTYPE` for my MacBook with M1 chip:
```
$ uname -m
arm64

$ echo $OSTYPE
darwin20.0
```
This make the value of `CMD` become `bin/darwin_/packr2` which cause the problem.

**Comment by nandahkrishna** [comment] 2021-06-11 20:46
Hello, Homebrew maintainer here. When https://github.com/Homebrew/homebrew-core/pull/79094 is merged, CircleCI CLI will be bottled (available via binary package) on ARM. We prefer using Homebrew formulae over vendors dependencies and in this case, that seemed to be the solution to getting CircleCI CLI built on M1.

I had some issues getting `packr` to work as intended and finally did manage to, but I thought I'd ask here if you'd be willing to move away from `packr`. The project doesn't seem to be actively maintained and there's a note on the README pointing to a replacement (see: [README](https://github.com/gobuffalo/packr#readme), https://github.com/gobuffalo/packr/issues/252 and https://github.com/gobuffalo/packr/issues/253).

Thanks!

**Comment by kelvintaywl** [comment] 2021-09-06 09:12
hello @llaenowyd , did you have any luck recently on this? 🤓 

I just wanted to mentioned that I am now able to install the CircleCI CLI via homebrew on Apple M1 successfully.

```
➜  ~ brew install circleci
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

==> Downloading https://ghcr.io/v2/homebrew/core/circleci/manifests/0.1.15932
Already downloaded: /Users/kelvin/Library/Caches/Homebrew/downloads/317ae4b4bacac9e9eb695531554cf923068b178cd728f2dc3a11eab426776215--circleci-0.1.15932.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/circleci/blobs/sha256:28b702cac
Already downloaded: /Users/kelvin/Library/Caches/Homebrew/downloads/42e9e1378ee3eabea6d2649d4c9d9eff255c8cc85b2a0f465fafe6fe329828df--circleci--0.1.15932.arm64_big_sur.bottle.tar.gz
==> Pouring circleci--0.1.15932.arm64_big_sur.bottle.tar.gz
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Summary
🍺  /opt/homebrew/Cellar/circleci/0.1.15932: 7 files, 14.2MB


➜  ~ circleci version

0.1.15932+3471602 (homebrew)
```
<img width="585" alt="Screen Shot 2021-09-06 at 18 06 12" src="https://user-images.githubusercontent.com/2164346/132191871-0d51fc3c-bd12-4e74-a740-186a6a266c8c.png">

**Comment by abdelDriowya** [comment] 2023-05-10 14:27
Closing as there's no answer from OP

**Closed by abdelDriowya** 2023-05-10 14:27 UTC
Labels: bug
