### ISSUE TITLE
"circleci orb init" fails if target directory and /tmp are on different file systems

### ISSUE THREAD

**Issue by isaac-s** [CircleCI-Public/circleci-cli#488] opened 2020-10-09 04:26 UTC
## Meta:

**CircleCI CLI Version:**
0.1.10699+026f9bf

**Operating System:**
Ubuntu 20.04

**CircleCI CLI Diagnostic:**

```
Debugger mode: false
Config found: /home/isaac/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API... 
Ok.
Hello, Isaac.
```
## Current behavior:

When using `circleci orb init <target-path>` and `<target-path>` is on a different file system than `/tmp`, an error occurs:

```
Error: rename /tmp/orb-project-template/CircleCI-Public-Orb-Project-Template-fda640c circleci-orb: invalid cross-device link
```

## Expected behavior:

Should work with no issue. Shouldn't attempt to rename across filesystems.

## When did this begin / Was this previously working?:

Never tried this before.

**Comment by gmemstr** [comment] 2020-10-19 13:55
Dupe of #491

**Closed by gmemstr** 2020-10-19 13:55 UTC
Labels: bug
