### ISSUE TITLE
Orb Info Doesn't work for Private Orbs

### ISSUE THREAD

**Issue by hud-code** [CircleCI-Public/circleci-cli#636] opened 2021-11-02 16:18 UTC
## Meta:

**CircleCI CLI Version:**
```
0.1.15663+6ec121d (homebrew)
0.1.16122+a170bd3 (homebrew)
```

**Operating System:**
MacOS

**CircleCI CLI Diagnostic:**

```
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/zacharyhudson/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
Hello, Zach.
```

---

## Current behavior:

```
>circleci orb list awesomecicd --private                                                                                                                                                     255 ↵
Orbs found: 1. Showing only private orbs.

awesomecicd/support-orb (Not published)

>circleci orb info awesomecicd/support-orb
Error: Failed to get info for 'awesomecicd/support-orb': Non-nullable field was null.
Something unexpected happened.
```

## Expected behavior:
Info should be provided for private orb

## Additional Information:
This feature was marked completed: https://ideas.circleci.com/orbs/p/allow-circleci-cli-commands-to-work-with-private-orbs

**Comment by abdelDriowya** [comment] 2023-11-07 14:53
closing because couldn't reproduce this issue 
0.1.28528+83956f7 (homebrew)

tested with 
```
 circleci orb list cci-internal --private   
 circleci orb info cci-internal/frontplane
```

**Closed** 2023-11-07 14:55 UTC
Labels: bug
