### ISSUE TITLE
Access denied error in local execute

### ISSUE THREAD

**Issue by rflaperuta** [CircleCI-Public/circleci-cli#118] opened 2018-09-20 22:44 UTC
When running `circleci local execute` in a python project, I got an access denied error bellow:

```
====>> Checkout code
  #!/bin/bash -eo pipefail
mkdir -p /home/circleci/alpe-skytef-gw && cp -r /tmp/_circleci_local_build_repo/. /home/circleci/alpe-skytef-gw
cp: cannot open '/tmp/_circleci_local_build_repo/./tests/__pycache__/test_inicializacao.cpython-36-PYTEST.pyc' for reading: Permission denied
Error: Exited with code 1
Step failed
Error: runner failed
Task failed
```

The thing is, when I clean all `__pycache__` dirs, it runs flawlessly.

Attached is the config.yml file, and the full error output running in verbose...
[error_report.txt](https://github.com/CircleCI-Public/circleci-cli/files/2403302/error_report.txt)
[config.txt](https://github.com/CircleCI-Public/circleci-cli/files/2403318/config.txt)

**Comment by eric-hu** [comment] 2019-02-26 07:04
Hi @rflaperuta ! Please forgive the late response. Can you try running `ls -la` on the "Permission denied" file to see who owns it?

**Comment by qurczak** [comment] 2019-06-06 10:59
The same problem.

version: 0.1.5607+f705856

$ circleci local execute
```
====>> Checkout code
  #!/bin/bash -eo pipefail
mkdir -p /home/circleci/repo && cd /tmp/_circleci_local_build_repo && git ls-files | tar -T - -c | tar -x -C /home/circleci/repo && cp -a /tmp/_circleci_local_build_repo/.git /home/circleci/repo
tar: docker/dockerfile/webapp/files/deploykey: Cannot open: Permission denied
tar: Exiting with failure status due to previous errors
Error: Exited with code 2
Step failed
```

This file is owned by me.

```
(venv3) $ ls -l docker/dockerfile/webapp/files/deploykey
-rw------- 1 m.winkler2 m.winkler2 1675 Apr  4 17:50 docker/dockerfile/webapp/files/deploykey

```

**Comment by marcomorain** [comment] 2020-03-10 14:38
This is a duplicate of #330

**Closed by marcomorain** 2020-03-10 14:38 UTC
Labels: Local Builds
